
name: Tests
on: 
   workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # Install OpenJDK from the AdoptOpenJDK distribution
        java-version: '21'
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.9 

    - name: Setup Ngrok
      run: sudo snap install ngrok && sudo ngrok config add-authtoken ${{ secrets.NGROK }}
      
    - name: Run server
      run: ipconfig &&  python start.py
